#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_c')
	opt.load('vala')

def configure(conf):
	conf.load('compiler_c vala')
	conf.check_cfg(package='glib-2.0', uselib_store='GLIB', atleast_version='2.32.1', mandatory=1, args='--cflags --libs')
	conf.check_cfg(package='gtk+-2.0', uselib_store='GTK', atleast_version='2.24.10', mandatory=1, args='--cflags --libs')
	conf.check_cfg(package='gee-1.0', uselib_store='GEE', atleast_version='0.6.4', mandatory=1, args='--cflags --libs')

def build(bld):
	bld.program(
		packages = 'gtk+-2.0 gee-1.0',
		target = 'AddressBookDemo',
		uselib = 'GTK GLIB GEE',
		source = ['ContactService.vala',
			'InMemoryContactService.vala',
			'TableModel.vala',
			'ContactTableModel.vala',
			'Main.vala',
			'TableView.vala',
			'Contact.vala',
			'MainWindow.vala',
			'EditContactDialog.vala',
			'TableColumn.vala'],
		vala_defines = ['DEBUG']
	)

